"""Package dùng chung: config, runtime, ingest và retrieval."""

from .config import (
    CHILD_DOCSTORE_PATH,
    COLLECTION_NAME,
    CURRENT_DIR,
    DATA_DIR,
    DEFAULT_GEMINI_MODEL_NAME,
    DEFAULT_QDRANT_BATCH_SIZE,
    DENSE_MODEL_NAME,
    GEMINI_OPENAI_BASE_URL,
    LIGHTRAG_INGEST_MANIFEST_PATH,
    LIGHTRAG_WORKSPACE,
    PARENT_DOCSTORE_PATH,
    QDRANT_DB_PATH,
    QDRANT_HOST,
    QDRANT_PORT,
    RAW_DATA_PATH,
    SPARSE_MODEL_NAME,
    _read_env_flag,
    _read_env_int,
    _read_env_str,
    _require_gemini_key,
    _resolve_gemini_max_concurrency,
    _resolve_gemini_model_name,
    _resolve_gemini_rpm_limit,
    _resolve_gemini_transient_max_retries,
    _resolve_lightrag_batch_size,
    _resolve_lightrag_max_parallel_insert,
    _resolve_qdrant_batch_size,
    _resolve_resume_existing_queue,
)
from .runtime import (
    DocStatus,
    EmbeddingFunc,
    LightRAG,
    compute_mdhash_id,
    openai_complete_if_cache,
    sanitize_text_for_encoding,
)
from .providers import (
    AsyncRequestRateLimiter,
    _build_gemini_llm_func,
    _extract_exception_status_code,
    _is_retryable_gemini_exception,
)
from .ingest_support import (
    _apply_test_mode_subset,
    _build_parent_ingest_records,
    _chunk_records,
    _fetch_doc_statuses,
    _get_status_attr,
    _load_ingest_manifest,
    _mark_manifest_record,
    _normalize_doc_status_value,
    _prepare_qdrant_collection,
    _resume_existing_pipeline_if_needed,
    _save_ingest_manifest,
    _validate_paths,
)
from .pipeline import hybrid_ingest, qdrant_ingest, lightrag_ingest
from .retriever import get_vector
from .context_builder import (
    _build_source_payload,
    _coerce_text,
    _format_context_items,
    _split_blocks,
)
from .text_utils import _lexical_score, build_query

__all__ = [
    # config
    "CHILD_DOCSTORE_PATH",
    "COLLECTION_NAME",
    "CURRENT_DIR",
    "DATA_DIR",
    "DEFAULT_GEMINI_MODEL_NAME",
    "DEFAULT_QDRANT_BATCH_SIZE",
    "DENSE_MODEL_NAME",
    "GEMINI_OPENAI_BASE_URL",
    "LIGHTRAG_INGEST_MANIFEST_PATH",
    "LIGHTRAG_WORKSPACE",
    "PARENT_DOCSTORE_PATH",
    "QDRANT_DB_PATH",
    "QDRANT_HOST",
    "QDRANT_PORT",
    "RAW_DATA_PATH",
    "SPARSE_MODEL_NAME",
    "_read_env_flag",
    "_read_env_int",
    "_read_env_str",
    "_require_gemini_key",
    "_resolve_gemini_max_concurrency",
    "_resolve_gemini_model_name",
    "_resolve_gemini_rpm_limit",
    "_resolve_gemini_transient_max_retries",
    "_resolve_lightrag_batch_size",
    "_resolve_lightrag_max_parallel_insert",
    "_resolve_qdrant_batch_size",
    "_resolve_resume_existing_queue",
    # runtime
    "DocStatus",
    "EmbeddingFunc",
    "LightRAG",
    "compute_mdhash_id",
    "openai_complete_if_cache",
    "sanitize_text_for_encoding",
    # providers
    "AsyncRequestRateLimiter",
    "_build_gemini_llm_func",
    "_extract_exception_status_code",
    "_is_retryable_gemini_exception",
    # ingest_support
    "_apply_test_mode_subset",
    "_build_parent_ingest_records",
    "_chunk_records",
    "_fetch_doc_statuses",
    "_get_status_attr",
    "_load_ingest_manifest",
    "_mark_manifest_record",
    "_normalize_doc_status_value",
    "_prepare_qdrant_collection",
    "_resume_existing_pipeline_if_needed",
    "_save_ingest_manifest",
    "_validate_paths",
    # pipeline
    "hybrid_ingest",
    "qdrant_ingest",
    "lightrag_ingest",
    # retrieval
    "get_vector",
    "_build_source_payload",
    "_coerce_text",
    "_format_context_items",
    "_split_blocks",
    "_lexical_score",
    "build_query",
]
